### ISSUE TITLE
No unread count on the tab icons

### ISSUE THREAD

**Issue by ralesk** [TwidereProject/Twidere-Android#266] opened 2015-12-08 21:12 UTC
I have a fresh install of Twidere on a new phone, but I've had this going on for a while on my tablet as well... I get notifications about new mentions and DMs, but the little overlay numbers of how many unread things there are, those don't appear.  This is regardless of the Unread count setting in Scrapyard.

**Comment by mariotaku** [comment] 2016-01-03 10:32
I think newest version has unread count, maybe you could try snapshots?

**Comment by ralesk** [comment] 2016-01-03 18:18
As usual (sadly), installing a snapshot recently rendered my Twidere entirely unusable and I reverted to the released version :(  It was the one last mentioned on Twitter.  It's extra uncomfortable because of having to reconfigure everything as a result.

**Comment by mariotaku** [comment] 2016-01-04 02:31
I remembered release version and snapshots has same signature, are you using f-droid versions?

**Comment by ralesk** [comment] 2016-01-04 09:19
No, I'm on normal Google Play usually

**Comment by mariotaku** [comment] 2016-02-04 19:51
I think this issues has been fixed in later commits.

**Comment by ralesk** [comment] 2016-02-06 09:30
I just installed 0131 and unfortunately still no unread counters

**Comment by mariotaku** [comment] 2016-02-06 11:12
What kind of tab doesn't show unread count?

**Comment by art1fa** [comment] 2016-02-06 11:44
same for me for every tab, but I thought I had them turned off somewhere - but didn't find it anymore :smile:

**Comment by mariotaku** [comment] 2016-02-06 12:16
I tried clean install without any configuration, and still unable to reproduce. Have you enable it in Settings - Scrapyard?

**Comment by art1fa** [comment] 2016-02-06 14:07
Yes, it is turned on. Maybe I can help you with any debug logs? Just tell me what to do ;)

**Comment by ralesk** [comment] 2016-02-06 15:15
Yes, I have disabled and then re-enabled in Scrapyard and still doesn't work.  It's not a clean install, but I'm reluctant to do that because then I'd have to enter my API key again...

**Comment by art1fa** [comment] 2016-02-13 12:23
After a clean install it worked for me again.

**Comment by ralesk** [comment] 2016-02-14 22:54
I just reinstalled and it still doesn't work I'm afraid.

**Comment by mariotaku** [comment] 2016-02-15 06:23
Could you show screencast or something? I'm not sure what goes wrong.

**Comment by craigtp** [comment] 2016-02-23 09:17
I'm currently running v3.0.6 and this is still a problem.   Unread counts are not appearing at all, irrespective of the setting in Scrapyard/Unread counts.

**Comment by innologi** [comment] 2016-02-23 14:40
I can confirm this. Hasn't worked for me since 0.3.0. Tried reinstalling 3.0.6 as well, but the issue persists regardless.

**Closed** 2017-04-08 14:39 UTC
Labels: type:bug
