### ISSUE TITLE
Following users on mastodon: 404 error

### ISSUE THREAD

**Issue by kr428** [TwidereProject/Twidere-Android#1277] opened 2020-04-26 07:11 UTC
Using Twidere with Mastodon, right now I can't follow any accounts.

Expected behaviour: Open some profile, tap on "+" symbol, follow account.

Actual behaviour: Open some profile, tap on "+", see a notification "404 error". Nothing else happens.

Using latest Play Store version on Android 9 / Lineage. Any other information I can provide to track this down? Or is it just me?

**Comment by Linkid** [comment] 2020-04-30 12:23
Hi !
I have the same issue with Mastodon accounts : I can follow ones on my instance, but not ones on different instances.
The version of my Twidere app is 4.1.0, but I reproduced it on older versions (since v3.7). I used F-Droid to get the app.
Thank you

**Comment by Linkid** [comment] 2020-04-30 14:27
Ok, I'll try a pull request !

**Comment by Tedko** [comment] 2020-05-01 15:35
@Linkid Thanks for the pr. We will use the branch maintenance for any new release etc. can you create another PR based on `maintenance` ? Lots of implementation in develop branch is deprecated. Will merge your pr to `maintenance` once you did a pr on that branch :)

**Comment by Tedko** [comment] 2020-05-01 16:35
fixed with https://github.com/TwidereProject/Twidere-Android/commit/fd55e70e6aa96fb66e5a618969e4fcdd43ffb094 since there's several change from `dev` branch to `maintenance` branch. Many thx @Linkid  -- can you take a look as well? I will close this issue first.

**Closed by Tedko** 2020-05-01 16:35 UTC
