### ISSUE TITLE
Images not displayed

### ISSUE THREAD

**Issue by invalidcyber** [TwidereProject/Twidere-Android#630] opened 2016-10-27 08:43 UTC
When I click on an image (which was not loaded before because of my parameters), there is the blue circle that indicates the image is loading. However, when it is complete, the rcreen stays black. Minitures do load most of the time. I have the problem both for videos and pictures.
Besides, image display sometimes work.

Images can be seen here :
https://framapic.org/gallery#UcBuIojdtvcS/tt1zUfh21zPr.png,Xjwz5RAyhQqt/phNaOVTvhT8b.png,O0oLaAoT3h0X/UKFRKxopa173.png,29sIGlZL2lGF/Z6I80DxK3AnY.png,MIBEqEj4T66y/7oUOfr7BSxaU.png,TTEzvnqpJBvG/MT0DI48s4dAd.png

```
Version: 3.2.8 (F-droid)
Device: Galaxy S3
Android Version: Android 6.0.1 Cyanogenmod 13 Nightly
```

How to reproduce

**Comment by invalidcyber** [comment] 2016-10-27 08:44
I haven't found yet a condition to reproduce this bug, since sometimes, image display doues work

**Comment by orithena** [comment] 2016-10-27 12:00
Can confirm this behaviour on my phone (Android 5.1.1). Sadly, I too cannot provide hard reproduction circumstances, which is why I didn't report it before.

To me, this smells like a timeout behaviour, but I don't see what the timeout is for. It certainly crops up more often on big images while being on a bad connection -- but in very rare cases also on WiFi. What's more puzzling: If I go back and try to load the image again, in rare cases it's already there, loaded from cache. Also, switching apps while waiting for the image to load seems to suspend the thread receiving the image, increasing the chance to break. Maybe the image loading needs to be moved to a service thread? But isn't it already on a service thread? I'm confused here.

In addition, the reload button that's displayed when an image failed to load does not seem to have any event handler associated with it.

Most of the time, I go with "Load in Browser" when the image failed to load. This works, then.

**Comment by orithena** [comment] 2016-10-27 15:50
Can confirm this behaviour on my phone (Android 5.1.1). Sadly, I too cannot provide hard reproduction circumstances, which is why I didn't report it before.

To me, this smells like a timeout behaviour, but I don't see what the timeout is for. It certainly crops up more often on big images while being on a bad connection -- but in very rare cases also on WiFi. What's more puzzling: If I go back and try to load the image again, in rare cases it's already there, loaded from cache. Also, switching apps while waiting for the image to load seems to suspend the thread receiving the image, increasing the chance to break. Maybe the image loading needs to be moved to a service thread? But isn't it already on a service thread? I'm confused here.

In addition, the reload button that's displayed when an image failed to load does not seem to have any event handler associated with it.

Most of the time, I go with "Load in Browser" when the image failed to load.

**Comment by sgargbugreporter** [comment] 2016-11-01 20:26
I have a similar issue.  (V 3.2.9, ANDROID 5.0, Lenovo A7000-a)
Can see the miniatures in the tweet, however clicking on the image brings a black background. Clicking the reload icon also does not solve the problem. "View in Browser" shows the entire tweet (from twitter).
However, in my case the reloading does not bring the image back. I am largely on WiFi and

**Comment by Rbagman** [comment] 2016-12-29 12:04
I have been experiencing the problem for over a year. 

It is not reproducible and has no rhyme or reason. Some images load fine and others load black; click image, reload and still black. I have tried clearing the cache and this has random results: may or may not help.

Android 4.4.2 Samsung GT-N7100

**Comment by rugk** [comment] 2018-02-10 11:37
Also see this. There is just a black screen and it either takes very long to load or whatever…

BTW I have the https://github.com/TwidereProject/Twidere-Android/issues/662 option (to now open a new "window" for loaded images) enabled.

**Comment by Tedko** [comment] 2020-04-09 12:37
@mariotaku can you reproduce this?

**Comment by rugk** [comment] 2020-04-11 23:33
Cannot reproduce this anymore.

**Comment by Tedko** [comment] 2020-04-13 04:52
Thanks. Will close this;)

**Closed** 2020-04-13 04:53 UTC
Labels: type:bug
