### ISSUE TITLE
Android 10 Gesture Navigation

### ISSUE THREAD

**Issue by JoshuaACasey** [TwidereProject/Twidere-Android#1216] opened 2019-09-18 16:12 UTC
Cannot access navigation drawer using gesture navigation on Android 10. To access navigation drawer, must turn off gesture navigation to re-enable the navigation buttons (which I personally want to avoid because I've gotten use to and like the gesture navigation)

## Extra info

Android version: 10

Network type:

- [x ] Cellular
- [ x] Wi-Fi

App version: (version code here)

Build variant:

- [ x] Google
- [ ] F-Droid

Micro-blogging service:

- [ x] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet
- [ x] Mastodon

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ x] [Official keys](https://gist.github.com/mariotaku/5465786)
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [ ] Media preview enabled

**Comment by elfrinjo** [comment] 2019-10-26 15:14
You can enable a permanent menu button in settings -> ...
However, that settings should bei turned on by default as gesture navigation ist now default too.

**Comment by Tlaster** [comment] 2020-04-15 05:08
Duplicate of #1223

**Closed by Tlaster** 2020-04-15 05:08 UTC

**Comment by rugk** [comment] 2020-09-11 14:58
Still does not work in Twidere 4.1.4? See https://github.com/TwidereProject/Twidere-Android/issues/1223#issuecomment-691145750
