### ISSUE TITLE
[Feature Request] Support Mastodon

### ISSUE THREAD

**Issue by rodneyrod** [TwidereProject/Twidere-Android#712] opened 2017-02-17 04:41 UTC
Mastodon is a new server for interacting with StatusNet networks, but it doesn't seem to use a client connection method that is compatible with existing StatusNet clients. Support for this will have to be added.

https://github.com/tootsuite/mastodon/blob/master/docs/Using-Mastodon/FAQ.md

**Comment by yvolk** [comment] 2017-03-16 15:59
A long story of this incompatibility is here (without any end though...) https://github.com/andstatus/andstatus/issues/419

**Comment by Lertsenem** [comment] 2017-04-03 08:01
If I understand well, Mastodon does not offer a StatusNet API by design. But it does offer a twitter-like API that Twidere could probably use with little adjustments.

**Comment by yvolk** [comment] 2017-04-03 15:57
"StatusNet API" _is_ the "Twitter compatible API". This is why I advised @Gargron to adopt it, for compatibility with existing clients.

**Comment by Gargron** [comment] 2017-04-03 16:01
The mastodon client API is only twitter-like in that all REST JSON APIs are like twitter's. The StatusNet API was bad, so I didn't copy it. We had good success creating apps for the Mastodon API, with lots of positive feedback from devs saying it's really straightforward and easy. It's all in the past anyway, don't see how discussing it is productive.

**Comment by Lertsenem** [comment] 2017-04-03 17:01
Nevermind the API, as a user the Twidere app is vastly more mature than what Tusky can offer now, and for quite some time I'm sure. Plus the multi account management is a killer feature for any user willing to migrate from Twitter to Mastodon.

@Gargron, I hear you when you say that the StatusNet API is bad, but would the cost of implementing it alongside your new API that high ? Would you reject PR aiming to do this or are you just not interested enough to do the work yourself ?

Separately, would the implementation of Mastodon API as an alternative in Twidere be doable ? Would it be hard ?

**Comment by yvolk** [comment] 2017-04-03 17:14
@Gargron I understood your "disappearance" from our discussion at https://github.com/andstatus/andstatus/issues/419 (that _you_ started) as you had no arguments to support your decision on API and you lost interest to implement it yourself... ?!

**Comment by mariotaku** [comment] 2017-04-03 17:15
Twidere can add support for other social platforms, as long as basic requirements met (users/status objects with unique id). It won't too hard technically speaking, however it would be a rather huge work to do. I'm willing to accept PRs that add Mastodon support.

**Comment by mariotaku** [comment] 2017-04-07 14:38
So here's what we need to support Mastodon:
- [x] OAuth 2 authorization (easy, a header is enough)
- [ ] Login flow
- [ ] Mastodon specific account info
- [ ] Mastodon objects (Posts, Users...)
- [ ] Mastodon API (See Twitter API for example, just need to annotate some interfaces)
- [ ] Utility classes converts Mastodon object to Twidere's `ParcelableXXX` object

Guys, since I have something else to do (iOS version and my work and my school works), could anyone help me doing tasks I've mentioned above? This can help this feature finished sooner.

**Comment by vanita5** [comment] 2017-04-07 16:13
I'm currently working with the Mastodon API and I'd love to implement this, but I'm afraid I won't have time 'till next weekend.

If anyone else is interested in helping out in the meantime, you can take a look at my node library regarding the login flow and how to get an access token: https://github.com/vanita5/mastodon-api

**Comment by mariotaku** [comment] 2017-04-18 15:14
I really should've give up any hope that anyone will help me with this feature. Is arguing about API more productive than implementing some features that can be done **within 3 days**?

**Comment by Lertsenem** [comment] 2017-04-18 15:19
Sorry, I would help but unfortunately I don't speak neither Java nor Kotlin. :/

**Comment by cyphar** [comment] 2017-04-19 12:11
Another thing to note that Twidere has above Tusky is that Twidere is actually available in FDroid. Tusky recently added proprietary requirements which made it non-free -- making it impossible to have a Mastodon app on your phone if you don't have the Play Store. I'm not a great Java developer (if I was I definitely would be helping out). :cry:

**Comment by mariotaku** [comment] 2017-04-21 18:58
What still needs to be done:
- [ ] Edit profile
- [ ] Follow/block/mute
- [ ] Set visibility for status
- [ ] Ensure account color set (by adding toParcelable(AccountDetails) maybe?)

**Comment by mariotaku** [comment] 2017-04-22 16:40
I guess this can be marked as done. Please test 3.5.23 version and help me to make sure every function is working properly.

**Comment by Lertsenem** [comment] 2017-04-22 20:29
Nice! Thank you so much!

**Comment by MightyPork** [comment] 2017-04-22 21:59
Some bugs I found while testing it:
- notifications and the like say 'tweet' instead of 'toot'
- the reply box has a 140 char limit (click 'reply' on a toot)
- "network public" timeline is not federated, but also local - so you get it twice
- apostrophes and maybe other things show as HTML entities
- getting lots of duplicate notifications (already dismissed)
- timelines don't seem to want to update unless I pull down

**Comment by Lertsenem** [comment] 2017-04-22 22:10
I found some others (testing 3.5.25). Should we write them here for the time being, or should we open new issues right now?

 - not only apostrophes, but line breaks are not properly rendered too
 - replying to a toot does not use the user full handle (only the username, not the instance), so the mentions cannot work out of the box for external users
 - when you use both a twitter and a mastodon account, modifying the interactions tab to print only the mastodon account notifs makes it unable to show follows/favs/RTs (only mentions)


> timelines don't seem to want to update unless I pull down

I couldn't reproduce this. Auto-refresh is working on my device.

**Comment by picsi** [comment] 2017-04-23 00:46
@mariotaku can you let us know when you push this update to F-Droid? Thanks.

**Comment by Hund** [comment] 2017-04-23 03:48
@picsi The guys over at F-Droid compiles the packages themselves.

**Comment by mariotaku** [comment] 2017-04-23 05:47
@Lertsenem 
> not only apostrophes, but line breaks are not properly rendered too

#779 

> replying to a toot does not use the user full handle (only the username, not the instance), so the mentions cannot work out of the box for external users

#780

**Comment by mariotaku** [comment] 2017-04-23 05:54
@MightyPork 
> notifications and the like say 'tweet' instead of 'toot'

Yes, this is because Twidere still uses Twitter's writing style, it will make text needed to translate multiplied if we add text for platforms respectively

> the reply box has a 140 char limit (click 'reply' on a toot)

You can set account color in 'Accounts' list.

> "network public" timeline is not federated, but also local

#777 

> apostrophes and maybe other things show as HTML entities

#773 

> getting lots of duplicate notifications

#770 

> timelines don't seem to want to update unless I pull down

#753 

> the hashtag tab is always empty

OK, I'll consider making this tab not added by default when a user login to mastodon instances 

> the DMs tab for some reason shows DMs from Twitter

Mastodon doesn't have DM feature yet.

**Comment by mariotaku** [comment] 2017-04-23 05:57
# Please, open separate issues rather than commenting here to make sure they get tracked respectively

**Comment by cyphar** [comment] 2017-04-23 08:44
@mariotaku 

>> the DMs tab for some reason shows DMs from Twitter
> Mastodon doesn't have DM feature yet.

OStatus (Mastodon) has different privacy preferences for messages, so "DMs" are supported, they're just not a separate communication method (you can send a message to someone that only you and they can read).

**Comment by mariotaku** [comment] 2017-04-23 08:46
@cyphar 'Direct' statuses in Mastodon still should be treated as status, because they mixed in notifications timeline. I'll make this DM conversation style only when it have related API to do that.

**Comment by cyphar** [comment] 2017-04-23 08:47
Fair enough, I was just pointing out that in OStatus I don't believe there is any plan to have "DMs" because privacy options fulfill that need in a more generic way.

**Comment by mariotaku** [comment] 2017-04-23 08:50
@cyphar Yeah, Mastodon's 'Direct' mentions are still not private enough since recipients may not respect this visibility.

**Closed** 2017-04-27 15:16 UTC
Labels: status:done, type:feature-request

**Comment by TanyaEleventhGoddess** [comment] 2019-08-05 12:43
This seems related, how do I accept mastodon friendship requests on twidere?
