### ISSUE TITLE
No sound when play video second time

### ISSUE THREAD

**Issue by ftpur** [TwidereProject/Twidere-Android#432] opened 2016-03-02 06:52 UTC
There is no sound when play video again after the first time. The first time is fine.

**Comment by benediktg** [comment] 2016-03-02 16:31
Could you please provide an example URL?

**Comment by ftpur** [comment] 2016-03-02 17:34
https://twitter.com/gobou_PTA/status/698374655250288640

(It happen to me every video that hosted on twitter.)

**Comment by benediktg** [comment] 2016-03-02 20:00
For me it seems to be fine. The first time I watch the video the sound is turned off by default. When I turn it on I can watch the video over and over again without the sound getting turned off.

**Comment by ftpur** [comment] 2016-03-02 20:16
Whether the sound turned on or not, there is no sound after the first time for me. (The sound icon didn't turn off itself. It stay on.) I use current (beta channel) version from play store.

**Comment by benediktg** [comment] 2016-03-02 21:07
Maybe there is a regression?

**Comment by mariotaku** [comment] 2017-02-07 15:17
Closing this issue, if this problem regressed, feel free to reopen or make a new issue.

**Closed by mariotaku** 2017-02-07 15:17 UTC
