### ISSUE TITLE
Notifications for received DMs don't work

### ISSUE THREAD

**Issue by diesocke** [TwidereProject/Twidere-Android#649] opened 2016-12-08 20:33 UTC
Using 3.2.9. Notifications for Direct Messages don't work, even though I've specifically set them via settings. Notifications for interactions work properly. Not sure if the missing notifications for DMs already occurred in former versions.

**Comment by Yowlen** [comment] 2017-01-31 09:38
This is a duplicate of #543.

**Closed** 2017-03-28 14:48 UTC
Labels: category:functionality, priority:medium, status:working, type:bug
