### ISSUE TITLE
ridiculously long delay to play video

### ISSUE THREAD

**Issue by clinty** [TwidereProject/Twidere-Android#666] opened 2016-12-19 17:23 UTC
When attempting to play [this terrible video](https://twitter.com/iammoshow/status/810882299709550592), Twidere takes ~20 minutes to start playback.

**Comment by orithena** [comment] 2016-12-19 17:36
Can't reproduce. Took 11 seconds here on WiFi.

Are you sure it isn't your connection? As far as I can see, Twidere waits until the whole video is loaded before starting playback.

**Comment by clinty** [comment] 2016-12-19 19:31
I was on WiFi without any apparent connection problems.  Android itself was unresponsive for a bit at the beginning.  The progress circle froze for a while in various places throughout the 20 minutes.

**Comment by mariotaku** [comment] 2017-04-03 08:33
After migrating to ExoPlayer2, this issue should be fixed, also video plays instantly once it begin loading.

**Closed by mariotaku** 2017-04-03 08:33 UTC
Labels: invalid:cant-reproduce
