### ISSUE TITLE
Browser Sign In Doesn't Work

### ISSUE THREAD

**Issue by BoringUserWhoCantCode** [TwidereProject/Twidere-Android#147] opened 2015-05-21 09:48 UTC
When I click the little browser icon, to add an account it says: "An error occurred, please try again".

I cycled through the authentication types just to test, none of them provide browser sign in except the default OAuth.

I also changed to the official API keys, still same error.

Can't sign into my account :(

Thanks for your efforts.

**info**
Nexus 5
Android 4.4.4
Twidere 0.3.0-dev-114

**Comment by dkirker** [comment] 2015-06-06 00:45
I can confirm that I have this problem. Since I don't think that it is possible to do Two-factor Auth any other way, I'm kinda stuck.... I'm trying to read the code to see if I can fix it myself.

**Comment by SnowGabe** [comment] 2015-06-22 17:50
I had to disable two-factor authentication on my Twitter account because of this issue.

**Comment by SnowGabe** [comment] 2015-06-22 17:51
A duplicate of #118.

**Comment by BoringUserWhoCantCode** [comment] 2015-06-22 17:57
@SnowGabe, this isn't a duplicate.

118 is about 2FA not working in User/Pass sign in.
This is about broken OAuth.

OAuth being a solution (if it worked) to 2FA doesn't make this a duplicate.

I reckon these are two distinct issues with different code solution.

**Comment by cygairko** [comment] 2015-07-06 14:37
Exception, when trying to open browser login screen:
https://gist.github.com/cygairko/9636c0d8a4a9ca76335d

**Comment by atoponce** [comment] 2015-08-20 20:07
Having the same issue with a new install on a clean phone.

**Comment by mariotaku** [comment] 2016-02-04 19:58
This should work now.

**Closed by mariotaku** 2016-02-04 19:58 UTC
Labels: bug
