### ISSUE TITLE
Load media from imgur

### ISSUE THREAD

**Issue by yamatt** [TwidereProject/Twidere-Android#370] opened 2016-02-13 17:43 UTC
Imgur links are not loaded in to the image preview. Is it possible to fix this?

**Comment by Zopieux** [comment] 2016-09-09 14:42
This is a duplicate of #275. Imgur checkbox is not checked yet! Contributions are welcome.

**Comment by Tedko** [comment] 2020-03-28 15:48
Duplicate with #275 . Will close this for now.
@yamatt @Zopieux Just let you know Twidere is back online and maintained by community, supported by https://dimension.im . Pls spread the word and let ppl know! We would like to bring as many community contributor as possible. Many thanks.

**Closed by Tedko** 2020-03-28 15:48 UTC
Labels: invalid:duplicate
