### ISSUE TITLE
Twidere tries to obtain location each time I open it / unlock lockscreen / start writing a tweet

### ISSUE THREAD

**Issue by newluck77** [TwidereProject/Twidere-Android#322] opened 2016-02-06 20:03 UTC
I have an unofficial Kitkat build for my FP1, which features a built-in app permission management.

### The issue
I denied location access to Twidere the first time, it asked me for it. Now I get a notification overlay each time, location access gets denied. Some sceenshots to illustrate my point:

This is after unlocking the lockscreen (note the notification overlay in the bottom of the screenshot):
![screenshot_2016-02-06-20-50-14 1](https://cloud.githubusercontent.com/assets/8948865/12869021/1ab02c18-cd14-11e5-810a-9ed67e37b061.png)

This is when I open Twidere:
![screenshot_2016-02-06-20-50-02 1](https://cloud.githubusercontent.com/assets/8948865/12869029/3ff9ab5c-cd14-11e5-9e70-bd94c0441660.png)

This is when I start writing a tweet (note that I don't attach my location to my tweet):
![screenshot_2016-02-06-19-15-25 1](https://cloud.githubusercontent.com/assets/8948865/12869043/7955554a-cd14-11e5-836b-2dd516123ca3.png)

### My questions:

- Is it intended behaviour, that Twidere wants my location in all the above occasions?
- If yes, how can I turn this behaviour off?
- If not: Which information, other then the below, do you need to fix this?

### My system

FP1 with MT6589 chip, running on Android KitKat 4.4.4 / Kernel Version 3.4.67

Cheers, :)

**Comment by mariotaku** [comment] 2016-02-07 07:43
1. Yes, this is an intended behavior, Twidere took part in an research program by Tsinghua University. It will get your cached location (so don't worry about battery drain)
2. If you don't want your location be used, you can go to Settings - Other - Usage Statistics to turn it off.
3. When I looked into my code, I found it doesn't disable location query when turn usage statistics off, this will get fixed in next commit.

**Closed** 2016-02-07 07:50 UTC
Labels: bug, question

**Comment by newluck77** [comment] 2016-02-07 11:12
Thank you for your fast reply and the fast fix (also in #323)! :+1: :D
