### ISSUE TITLE
2015-06-29 release displays bad dates in timeline

### ISSUE THREAD

**Issue by ralesk** [TwidereProject/Twidere-Android#182] opened 2015-06-29 15:12 UTC
I see one post from each displayed account, both are dated to december 26th, but neither of those happened back then (one of them is merely half a day old: https://twitter.com/marcelgruenauer/status/615062850885824512)

The times are weird for the top few posts, one is even in the future.

![screenshot_2015-06-29-17-05-45 x](https://cloud.githubusercontent.com/assets/1564502/8411020/f30f2cd6-1e81-11e5-983a-f32022356a53.png)

**Comment by wjzijderveld** [comment] 2015-06-30 05:31
I can confirm this, I see 2 old tweets on top of my timeline, there are also 2 old tweets (different tweets) above my mention timeline.

**Comment by jacroe** [comment] 2015-06-30 18:07
I had this too. I managed to fix it (for now) by going to the Settings > Storage > Clear databases. This caused the old tweets (December 26 for me too, weird) to go away.

**Comment by ralesk** [comment] 2015-07-01 09:04
Clearing databases didn't solve it for me, now I have mentions that are mistimed.

**Comment by mariotaku** [comment] 2015-07-01 15:02
Is your tinezone settings in your phone right?

**Comment by ralesk** [comment] 2015-07-01 15:05
Nothing special about it. It's CEST and has been for a while before I updated.  I did go to Singapore a few weeks ago, but the previous beta client did not get confused about it at all.

(btw, do you also get the few pixels gap on the top of the timeline too? like on my screenshot)

**Comment by declangao** [comment] 2015-07-02 03:05
I've seen tweets dated three days into the future since the latest update. Because it's from the "future", it always stays at the top of the list. Clicking into the tweet seems to resolve the issue.

**Comment by ralesk** [comment] 2015-09-03 08:27
Still ongoing.  Cleared the database several times, certain items end up on top because they're in the future (they really aren't).

**Comment by mariotaku** [comment] 2015-09-04 03:49
I added an error report for this before. After rewrote date parsing component, I found there's no further reports after 33db1f5d19c264f5c21f4731d207e96b56c13b62. You could update to dev150903 version and see again, that should fix date problem.

**Comment by ralesk** [comment] 2015-09-04 08:39
Several database cleanings didn't help with the latest release as of yesterday, but when I reinstalled due to #208 I didn't get any timeline artifacts like this...

There might be something incomplete about the update.

**Comment by mariotaku** [comment] 2016-02-04 23:37
This should get fixed now.

**Closed by mariotaku** 2016-02-04 23:37 UTC
Labels: bug
