### ISSUE TITLE
Twidere stops when sending tweet with image

### ISSUE THREAD

**Issue by ghc0000** [TwidereProject/Twidere-Android#757] opened 2017-04-11 03:53 UTC
As the title describes, tweets with images seem to fail. Image size I tried are about 1MB so they should not be too big for uploading.

Android version: 6.0.1

Network type: Cellular

App version: 3.5.8

Build variant:
- [x] Google
- [ ] F-Droid

Micro-blogging service:

- [x] Twitter
- [ ] Fanfou
- [ ] GNU Social / StatusNet

App settings:

- [ ] Custom API
- [ ] Custom consumer key/secrets
- [ ] Official keys
- [ ] Using [Thumbor](https://github.com/thumbor/thumbor)
- [ ] Connected through proxy
- [x] Media preview enabled

**Comment by mariotaku** [comment] 2017-04-11 05:21
Confirmed and fixed in 3.5.9, it's caused by a Nougat-only api invocation.

**Closed by mariotaku** 2017-04-11 05:21 UTC
Labels: category:functionality, priority:high, status:done, type:bug
