### ISSUE TITLE
Twidere crashes when trying to fetch new messages

### ISSUE THREAD

**Issue by benediktg** [TwidereProject/Twidere-Android#304] opened 2016-01-28 16:38 UTC
I have set up a GNU social and a Twitter account in Twidere and every time I try to load new messages (by swiping down when I'm at the top of the timeline), Twidere crashes with an entry like the following in the logs:
```01-27 21:47:32.641 E/AndroidRuntime(18865): 	at org.mariotaku.twidere.util.AsyncTwitterWrapper$GetSavedSearchesTask.doInBackground(AsyncTwitterWrapper.java:602)```

After I have started Twidere again the new messages are visible. In addition to that the option to load missing messages between older ones works without this problem.

The Twidere version is 0.3.0 (dev 2016-01-26) – some days ago I had the latest version from F-Droid with only a Twitter account set up and this also had worked just fine…

**Comment by mariotaku** [comment] 2016-01-29 03:07
This may caused by a known bug #295, please try re-download 2016-01-26 version.

**Comment by mariotaku** [comment] 2016-02-01 15:22
Is 0131 work for you?

**Comment by benediktg** [comment] 2016-02-01 15:52
No, unfortunately neither redownloading 20160126 nor installing 20160131 did help with this issue.

**Comment by mariotaku** [comment] 2016-02-01 17:03
Can you provide more crash logs?

**Comment by benediktg** [comment] 2016-02-01 22:43
This is what I get after trying to load new messages two times (with Twitter and GNU social account enabled).

[2016-02-01-23-38-57.txt](https://github.com/TwidereProject/Twidere-Android/files/113117/2016-02-01-23-38-57.txt)

**Comment by mariotaku** [comment] 2016-02-04 09:27
fixed in 7a85746eeb91ed8ec12dcf9faa9c4d41a66ad935.

**Closed by mariotaku** 2016-02-04 09:27 UTC
