### ISSUE TITLE
losing scrolling position when screen auto-rotates

### ISSUE THREAD

**Issue by braparb** [TwidereProject/Twidere-Android#462] opened 2016-03-18 13:07 UTC
Hey everyone,

I often encounter the problem that I loose my scrolling position once my mobile's screen auto rotates. The view then automatically jumps to the top again once I turn the screen in upright position again. Is there a way to tackle this issue?

**Comment by pauledwin** [comment] 2016-03-30 12:58
Possible duplicate of #277

**Comment by benediktg** [comment] 2016-03-30 13:12
And I unfortunately cannot reproduce this issue with Twidere v3.1.1.6 from F-Droid. The scrolling positions stays the same – no matter how often I rotate the screen.

**Comment by braparb** [comment] 2016-03-30 13:18
Okay, thanks anyway so far. I think it is slightly different from #277 since it doesn't refresh my TL but just jumps to the top (the most recent tweet of the last time i refreshed)...

**Closed** 2017-02-07 15:18 UTC
Labels: invalid:cant-reproduce
